# Generated by Django 5.2.17 on 2026-09-22 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_modeldownload_visitor_id_project_print_count_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('guidance', 'Guidance'), ('template', 'Template')], default='guidance', max_length=16)),
                ('template_key', models.CharField(blank=True, default='', max_length=64)),
                ('object_kind', models.CharField(blank=True, default='', max_length=64)),
                ('guidance', models.TextField(blank=True)),
                ('defaults_json', models.JSONField(blank=True, default=dict)),
                ('constraints_json', models.JSONField(blank=True, default=dict)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skills', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='skills', to='projects.tag')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
