# Generated by Django 5.2.17 on 2026-09-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_modeldownload_visitor_id_project_print_count_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='skills.skill'),
        ),
    ]
