"""Tests for the headless G-code -> PNG preview renderer (terv.md Phase 5).

The renderer must be deterministic and dependency-light: parsing is pure Python
and rasterisation goes through Pillow, with no shell/network/GPU. These tests
assert observable properties (PNG signature, dimensions, segment counts) so they
stay robust across Pillow versions.
"""

from __future__ import annotations

import io

import pytest

from slicers.preview import (
    PreviewRenderError,
    parse_extrusion_segments,
    render_gcode_preview,
)

PNG_MAGIC = b"\x89PNG\r\n\x1a\n"

#: One square spiral: ``G1 X0 Y0 E0`` is a travel, the three following moves
#: extrude; the fourth repeats the absolute ``E`` word and must not be drawn.
SQUARE_GCODE = (
    b"; generated by a test\n"
    b"G1 X0 Y0 E0\n"
    b"G1 X10 Y0 E1.0\n"
    b"G1 X10 Y10 E2.0\n"
    b"G1 X0 Y10 E2.0\n"
    b"G1 X0 Y0 E2.5\n"
    b"G1 Z0.2\n"
    b"G1 X20 Y0 E3.5\n"
)


def _png_size(payload: bytes) -> tuple[int, int]:
    from PIL import Image

    with Image.open(io.BytesIO(payload)) as image:
        return image.size


# ---------------------------------------------------------------------------
# parser
# ---------------------------------------------------------------------------


def test_parser_extracts_extruding_moves_only():
    segments = parse_extrusion_segments(SQUARE_GCODE)

    assert len(segments) == 4
    assert segments[0] == pytest.approx((0.0, 0.0, 10.0, 0.0, 0.0))
    # The repeated ``E2.0`` move is a travel and is skipped; the ``E2.5`` move is
    # drawn from the last real position ``(0, 10)`` back to ``(0, 0)``.
    assert segments[2] == pytest.approx((0.0, 10.0, 0.0, 0.0, 0.0))
    # After ``G1 Z0.2`` the next extrusion carries the new layer Z.
    assert segments[3].z == pytest.approx(0.2)
    assert segments[3] == pytest.approx((0.0, 0.0, 20.0, 0.0, 0.2))


def test_parser_tracks_relative_extrusion_and_xyz():
    gcode = b"M83\nG91\nG1 X5 Y0 E1.0\nG1 X0 Y5 E0.5\n"
    segments = parse_extrusion_segments(gcode)

    assert len(segments) == 2
    assert segments[0] == pytest.approx((0.0, 0.0, 5.0, 0.0, 0.0))
    assert segments[1] == pytest.approx((5.0, 0.0, 5.0, 5.0, 0.0))


def test_parser_honours_g92_reset():
    gcode = b"G1 X0 Y0 E0\nG1 X10 Y0 E5\nG92 E0\nG1 X10 Y10 E1\n"
    segments = parse_extrusion_segments(gcode)

    assert len(segments) == 2
    assert segments[1] == pytest.approx((10.0, 0.0, 10.0, 10.0, 0.0))


def test_parser_caps_the_segment_count():
    lines = [b"G1 X0 Y0 E0\n"]
    for index in range(1, 50):
        lines.append(f"G1 X{index} Y0 E{index}.0\n".encode())
    gcode = b"".join(lines)

    segments = parse_extrusion_segments(gcode, max_segments=5)

    assert len(segments) == 5


def test_parser_accepts_compact_spelling():
    segments = parse_extrusion_segments(b"G1X10Y10E1\n")
    assert len(segments) == 1
    assert segments[0] == pytest.approx((0.0, 0.0, 10.0, 10.0, 0.0))


def test_parser_rejects_empty_input():
    with pytest.raises(PreviewRenderError):
        parse_extrusion_segments(b"")


@pytest.mark.parametrize("payload", [b"not gcode at all", b"\x00\x01\x02\x03"])
def test_parser_degrades_to_no_segments_for_garbage(payload):
    assert parse_extrusion_segments(payload) == []


def test_parser_rejects_non_bytes():
    with pytest.raises(PreviewRenderError):
        parse_extrusion_segments("G1 X10 Y10 E1")  # type: ignore[arg-type]


def test_parser_rejects_bad_max_segments():
    with pytest.raises(PreviewRenderError):
        parse_extrusion_segments(SQUARE_GCODE, max_segments=0)


# ---------------------------------------------------------------------------
# renderer
# ---------------------------------------------------------------------------


def test_render_returns_square_png():
    png = render_gcode_preview(SQUARE_GCODE, size=256)

    assert png.startswith(PNG_MAGIC)
    assert len(png) > 500
    assert _png_size(png) == (256, 256)


def test_render_is_deterministic():
    assert render_gcode_preview(SQUARE_GCODE, size=128) == render_gcode_preview(
        SQUARE_GCODE, size=128
    )


def test_render_draws_dark_pixels_on_white():
    from PIL import Image

    png = render_gcode_preview(SQUARE_GCODE, size=128)
    with Image.open(io.BytesIO(png)) as image:
        colors = {pixel for _, pixel in image.getcolors(maxcolors=1 << 20)}

    assert (255, 255, 255) in colors
    assert any(max(color) < 200 for color in colors)


def test_render_degrades_on_a_huge_segment_stream():
    lines = [b"G1 X0 Y0 E0\n"]
    for index in range(1, 5000):
        lines.append(f"G1 X{index % 100} Y{index // 100} E{index}.0\n".encode())
    gcode = b"".join(lines)

    png = render_gcode_preview(gcode, size=64, max_segments=100)

    assert png.startswith(PNG_MAGIC)
    assert len(parse_extrusion_segments(gcode, max_segments=100)) == 100


def test_render_rejects_gcode_without_extrusion():
    with pytest.raises(PreviewRenderError):
        render_gcode_preview(b"; only comments\nG1 X10 Y10\nG0 X0 Y0\n")


@pytest.mark.parametrize("size", [0, 8, -1, 10_000, "512", None, True])
def test_render_rejects_invalid_size(size):
    with pytest.raises(PreviewRenderError):
        render_gcode_preview(SQUARE_GCODE, size=size)  # type: ignore[arg-type]


def test_render_rejects_empty_input():
    with pytest.raises(PreviewRenderError):
        render_gcode_preview(b"")


@pytest.mark.parametrize("payload", [b"not gcode at all", b"\x00\x01\x02\x03"])
def test_render_rejects_garbage(payload):
    with pytest.raises(PreviewRenderError):
        render_gcode_preview(payload)
