# Generated by Django 5.2.17 on 2026-09-21 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ollama_base_url', models.URLField(blank=True)),
                ('ollama_model', models.CharField(blank=True, max_length=200)),
                ('embedding_model', models.CharField(blank=True, max_length=200)),
                ('rag_enabled', models.BooleanField(blank=True, null=True)),
                ('openscad_mode', models.CharField(blank=True, choices=[('local', 'local'), ('docker', 'docker')], max_length=20)),
                ('openscad_timeout_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('openscad_memory_limit', models.CharField(blank=True, max_length=20)),
                ('openscad_cpu_limit', models.CharField(blank=True, max_length=20)),
                ('slicer_mode', models.CharField(blank=True, choices=[('local', 'local'), ('docker', 'docker')], max_length=20)),
                ('slicer_timeout_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_backend', models.CharField(blank=True, choices=[('local', 'local')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'app settings',
                'verbose_name_plural': 'app settings',
            },
        ),
    ]
