# Generated by Django 5.2.17 on 2026-09-21 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaPull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('completed_bytes', models.BigIntegerField(blank=True, null=True)),
                ('total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ollama_pulls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ollama pull',
                'ordering': ['-created_at'],
            },
        ),
    ]
