# Generated by Django 5.2.17 on 2026-09-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_ollamapull'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='ollama_vision_model',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
