# Generated by Django 5.2.17 on 2026-09-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_appsettings_ollama_vision_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='llm_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mcp_service_user_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='openai_base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='search_backend',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='searxng_base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='storage_backend',
            field=models.CharField(blank=True, choices=[('local', 'local'), ('s3', 's3')], max_length=20),
        ),
    ]
