# Generated by Django 5.2.17 on 2026-09-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_appsettings_llm_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='openai_model',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
