# Generated by Django 5.2.17 on 2026-09-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_appsettings_openai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='ollama_timeout',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
