# Generated by Django 5.2.17 on 2026-09-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_appsettings_ollama_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ollamapull',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
