# Generated by Django 5.2.17 on 2026-09-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_ollamapull_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='mesh_backend',
            field=models.CharField(blank=True, choices=[('mesh', 'mesh')], max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mesh_default_scale_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mesh_max_source_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mesh_repair_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mesh_target_faces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
