# Generated by Django 5.2.17 on 2026-09-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_appsettings_mesh_backend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='ollama_context_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
