# Generated by Django 5.2.17 on 2026-09-21 12:53

import designs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('prompt', models.TextField(blank=True)),
                ('specification_json', models.JSONField(blank=True, default=dict)),
                ('validation_json', models.JSONField(blank=True, default=dict)),
                ('scad_file', models.FileField(blank=True, upload_to=designs.models.model_artifact_path)),
                ('stl_file', models.FileField(blank=True, upload_to=designs.models.model_artifact_path)),
                ('glb_file', models.FileField(blank=True, upload_to=designs.models.model_artifact_path)),
                ('preview_image', models.ImageField(blank=True, upload_to=designs.models.model_artifact_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project')),
            ],
            options={
                'ordering': ['project', '-version'],
                'constraints': [models.UniqueConstraint(fields=('project', 'version'), name='uniq_model_version_per_project')],
            },
        ),
    ]
