# Generated by Django 5.2.17 on 2026-09-21 20:49

import designs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='reference_image',
            field=models.ImageField(blank=True, upload_to=designs.models.model_artifact_path),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='reference_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
