# Generated by Django 5.2.17 on 2026-09-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_modelversion_reference_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='annotations_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='designs.modelversion'),
        ),
    ]
