# Generated by Django 5.2.17 on 2026-09-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_modelversion_annotations_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='origin',
            field=models.CharField(choices=[('generate', 'Generate'), ('annotation', 'Annotation'), ('regenerate', 'Regenerate'), ('manual', 'Manual')], default='generate', max_length=16),
        ),
    ]
