# Generated by Django 5.2.17 on 2026-09-27 12:27

import designs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_modelversion_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='source_mesh',
            field=models.FileField(blank=True, help_text='Optional source mesh (.stl/.obj/.glb) for the mesh-import CAD backend.', upload_to=designs.models.model_artifact_path),
        ),
    ]
