# Generated by Django 5.2.17 on 2026-09-21 13:08

import django.db.models.deletion
import printers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        ('projects', '0001_initial'),
        ('slicers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('backend', models.CharField(blank=True, max_length=50)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcode', models.FileField(blank=True, upload_to=printers.models.print_job_gcode_path)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PREPARING', 'Preparing'), ('SLICING', 'Slicing'), ('READY', 'Ready'), ('PRINTING', 'Printing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_print_jobs', to=settings.AUTH_USER_MODEL)),
                ('filament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='slicers.filamentprofile')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='designs.modelversion')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='printers.printer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='projects.project')),
                ('slicer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='slicers.processprofile')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
