# Generated by Django 5.2.17 on 2026-09-21 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
        ('slicers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='printer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='slicers.printerprofile'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='slicing_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
