# Generated by Django 5.2.17 on 2026-09-21 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_modelversion_reference_image_and_more'),
        ('printers', '0003_create_operate_printer_permission'),
        ('projects', '0002_tag_project_description_source_and_more'),
        ('slicers', '0002_buildplate_plateitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='build_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='slicers.buildplate'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='designs.modelversion'),
        ),
        migrations.AddConstraint(
            model_name='printjob',
            constraint=models.CheckConstraint(condition=models.Q(('model_version__isnull', False), ('build_plate__isnull', False), _connector='OR'), name='print_job_has_target'),
        ),
    ]
