# Generated by Django 5.2.17 on 2026-09-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_printjob_build_plate_alter_printjob_model_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
