# Generated by Django 5.2.17 on 2026-09-21 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_modelversion_reference_image_and_more'),
        ('projects', '0002_tag_project_description_source_and_more'),
        ('slicers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_build_plates', to=settings.AUTH_USER_MODEL)),
                ('printer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_plates', to='slicers.printerprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_plates', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('scale', models.FloatField(default=1.0)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='slicers.buildplate')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_items', to='designs.modelversion')),
            ],
            options={
                'ordering': ['build_plate', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='buildplate',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_build_plate_name_per_project'),
        ),
    ]
